// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Basic.pb.h"
#import "User.pb.h"

@class PBAction;
@class PBAction_Builder;
@class PBActivity;
@class PBActivity_Builder;
@class PBAlbum;
@class PBAlbum_Builder;
@class PBBriefUser;
@class PBBriefUser_Builder;
@class PBComment;
@class PBComment_Builder;
@class PBContact;
@class PBContact_Builder;
@class PBDevice;
@class PBDevice_Builder;
@class PBJoin;
@class PBJoin_Builder;
@class PBLocation;
@class PBLocation_Builder;
@class PBLog;
@class PBLog_Builder;
@class PBMerchant;
@class PBMerchant_Builder;
@class PBParty;
@class PBParty_Builder;
@class PBPromotion;
@class PBPromotion_Builder;
@class PBRegistration;
@class PBRegistration_Builder;
@class PBSNS;
@class PBSNS_Builder;
@class PBShare;
@class PBShare_Builder;
@class PBShopping;
@class PBShopping_Builder;
@class PBStatistic;
@class PBStatistic_Builder;
@class PBTraffic;
@class PBTraffic_Builder;
@class PBUser;
@class PBUserBasic;
@class PBUserBasic_Builder;
@class PBUser_Builder;
typedef enum {
  PBActivityTypeParty = 1,
  PBActivityTypeTraffic = 2,
  PBActivityTypeShopping = 3,
} PBActivityType;

BOOL PBActivityTypeIsValidValue(PBActivityType value);

typedef enum {
  PBActionTypeActivity = 1,
  PBActionTypeShare = 2,
  PBActionTypeJoin = 3,
} PBActionType;

BOOL PBActionTypeIsValidValue(PBActionType value);

typedef enum {
  PBActionStatusNormal = 1,
  PBActionStatusDeleted = 2,
  PBActionStatusMark = 3,
} PBActionStatus;

BOOL PBActionStatusIsValidValue(PBActionStatus value);

typedef enum {
  PBPayTypeAa = 1,
  PBPayTypeFree = 2,
  PBPayTypeOther = 10,
} PBPayType;

BOOL PBPayTypeIsValidValue(PBPayType value);


@interface ActionRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PBAlbum : PBGeneratedMessage {
@private
  BOOL hasAlbumId_:1;
  BOOL hasUid_:1;
  BOOL hasName_:1;
  NSString* albumId;
  NSString* uid;
  NSString* name;
  NSMutableArray* mutableImageListList;
}
- (BOOL) hasAlbumId;
- (BOOL) hasUid;
- (BOOL) hasName;
@property (readonly, retain) NSString* albumId;
@property (readonly, retain) NSString* uid;
@property (readonly, retain) NSString* name;
- (NSArray*) imageListList;
- (NSString*) imageListAtIndex:(int32_t) index;

+ (PBAlbum*) defaultInstance;
- (PBAlbum*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBAlbum_Builder*) builder;
+ (PBAlbum_Builder*) builder;
+ (PBAlbum_Builder*) builderWithPrototype:(PBAlbum*) prototype;

+ (PBAlbum*) parseFromData:(NSData*) data;
+ (PBAlbum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAlbum*) parseFromInputStream:(NSInputStream*) input;
+ (PBAlbum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAlbum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBAlbum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBAlbum_Builder : PBGeneratedMessage_Builder {
@private
  PBAlbum* result;
}

- (PBAlbum*) defaultInstance;

- (PBAlbum_Builder*) clear;
- (PBAlbum_Builder*) clone;

- (PBAlbum*) build;
- (PBAlbum*) buildPartial;

- (PBAlbum_Builder*) mergeFrom:(PBAlbum*) other;
- (PBAlbum_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBAlbum_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAlbumId;
- (NSString*) albumId;
- (PBAlbum_Builder*) setAlbumId:(NSString*) value;
- (PBAlbum_Builder*) clearAlbumId;

- (BOOL) hasUid;
- (NSString*) uid;
- (PBAlbum_Builder*) setUid:(NSString*) value;
- (PBAlbum_Builder*) clearUid;

- (BOOL) hasName;
- (NSString*) name;
- (PBAlbum_Builder*) setName:(NSString*) value;
- (PBAlbum_Builder*) clearName;

- (NSArray*) imageListList;
- (NSString*) imageListAtIndex:(int32_t) index;
- (PBAlbum_Builder*) replaceImageListAtIndex:(int32_t) index with:(NSString*) value;
- (PBAlbum_Builder*) addImageList:(NSString*) value;
- (PBAlbum_Builder*) addAllImageList:(NSArray*) values;
- (PBAlbum_Builder*) clearImageListList;
@end

@interface PBComment : PBGeneratedMessage {
@private
  BOOL hasIsReply_:1;
  BOOL hasCDate_:1;
  BOOL hasStar_:1;
  BOOL hasCommentId_:1;
  BOOL hasStringId_:1;
  BOOL hasUid_:1;
  BOOL hasContent_:1;
  BOOL hasReplyId_:1;
  BOOL hasDigest_:1;
  BOOL isReply_:1;
  int32_t cDate;
  int32_t star;
  NSString* commentId;
  NSString* stringId;
  NSString* uid;
  NSString* content;
  NSString* replyId;
  NSString* digest;
}
- (BOOL) hasCommentId;
- (BOOL) hasStringId;
- (BOOL) hasUid;
- (BOOL) hasCDate;
- (BOOL) hasContent;
- (BOOL) hasStar;
- (BOOL) hasIsReply;
- (BOOL) hasReplyId;
- (BOOL) hasDigest;
@property (readonly, retain) NSString* commentId;
@property (readonly, retain) NSString* stringId;
@property (readonly, retain) NSString* uid;
@property (readonly) int32_t cDate;
@property (readonly, retain) NSString* content;
@property (readonly) int32_t star;
- (BOOL) isReply;
@property (readonly, retain) NSString* replyId;
@property (readonly, retain) NSString* digest;

+ (PBComment*) defaultInstance;
- (PBComment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBComment_Builder*) builder;
+ (PBComment_Builder*) builder;
+ (PBComment_Builder*) builderWithPrototype:(PBComment*) prototype;

+ (PBComment*) parseFromData:(NSData*) data;
+ (PBComment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBComment*) parseFromInputStream:(NSInputStream*) input;
+ (PBComment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBComment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBComment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBComment_Builder : PBGeneratedMessage_Builder {
@private
  PBComment* result;
}

- (PBComment*) defaultInstance;

- (PBComment_Builder*) clear;
- (PBComment_Builder*) clone;

- (PBComment*) build;
- (PBComment*) buildPartial;

- (PBComment_Builder*) mergeFrom:(PBComment*) other;
- (PBComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCommentId;
- (NSString*) commentId;
- (PBComment_Builder*) setCommentId:(NSString*) value;
- (PBComment_Builder*) clearCommentId;

- (BOOL) hasStringId;
- (NSString*) stringId;
- (PBComment_Builder*) setStringId:(NSString*) value;
- (PBComment_Builder*) clearStringId;

- (BOOL) hasUid;
- (NSString*) uid;
- (PBComment_Builder*) setUid:(NSString*) value;
- (PBComment_Builder*) clearUid;

- (BOOL) hasCDate;
- (int32_t) cDate;
- (PBComment_Builder*) setCDate:(int32_t) value;
- (PBComment_Builder*) clearCDate;

- (BOOL) hasContent;
- (NSString*) content;
- (PBComment_Builder*) setContent:(NSString*) value;
- (PBComment_Builder*) clearContent;

- (BOOL) hasStar;
- (int32_t) star;
- (PBComment_Builder*) setStar:(int32_t) value;
- (PBComment_Builder*) clearStar;

- (BOOL) hasIsReply;
- (BOOL) isReply;
- (PBComment_Builder*) setIsReply:(BOOL) value;
- (PBComment_Builder*) clearIsReply;

- (BOOL) hasReplyId;
- (NSString*) replyId;
- (PBComment_Builder*) setReplyId:(NSString*) value;
- (PBComment_Builder*) clearReplyId;

- (BOOL) hasDigest;
- (NSString*) digest;
- (PBComment_Builder*) setDigest:(NSString*) value;
- (PBComment_Builder*) clearDigest;
@end

@interface PBPromotion : PBGeneratedMessage {
@private
  BOOL hasStartDate_:1;
  BOOL hasEndDate_:1;
  BOOL hasContent_:1;
  int32_t startDate;
  int32_t endDate;
  NSString* content;
}
- (BOOL) hasStartDate;
- (BOOL) hasEndDate;
- (BOOL) hasContent;
@property (readonly) int32_t startDate;
@property (readonly) int32_t endDate;
@property (readonly, retain) NSString* content;

+ (PBPromotion*) defaultInstance;
- (PBPromotion*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBPromotion_Builder*) builder;
+ (PBPromotion_Builder*) builder;
+ (PBPromotion_Builder*) builderWithPrototype:(PBPromotion*) prototype;

+ (PBPromotion*) parseFromData:(NSData*) data;
+ (PBPromotion*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPromotion*) parseFromInputStream:(NSInputStream*) input;
+ (PBPromotion*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPromotion*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBPromotion*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBPromotion_Builder : PBGeneratedMessage_Builder {
@private
  PBPromotion* result;
}

- (PBPromotion*) defaultInstance;

- (PBPromotion_Builder*) clear;
- (PBPromotion_Builder*) clone;

- (PBPromotion*) build;
- (PBPromotion*) buildPartial;

- (PBPromotion_Builder*) mergeFrom:(PBPromotion*) other;
- (PBPromotion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBPromotion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStartDate;
- (int32_t) startDate;
- (PBPromotion_Builder*) setStartDate:(int32_t) value;
- (PBPromotion_Builder*) clearStartDate;

- (BOOL) hasEndDate;
- (int32_t) endDate;
- (PBPromotion_Builder*) setEndDate:(int32_t) value;
- (PBPromotion_Builder*) clearEndDate;

- (BOOL) hasContent;
- (NSString*) content;
- (PBPromotion_Builder*) setContent:(NSString*) value;
- (PBPromotion_Builder*) clearContent;
@end

@interface PBMerchant : PBGeneratedMessage {
@private
  BOOL hasLat_:1;
  BOOL hasLng_:1;
  BOOL hasRate_:1;
  BOOL hasCost_:1;
  BOOL hasImgUrl_:1;
  BOOL hasWapUrl_:1;
  BOOL hasWebUrl_:1;
  BOOL hasSiteUrl_:1;
  BOOL hasWorkTime_:1;
  BOOL hasDesc_:1;
  BOOL hasCate_:1;
  BOOL hasTel_:1;
  BOOL hasAddr_:1;
  BOOL hasCounty_:1;
  BOOL hasName_:1;
  BOOL hasAibangId_:1;
  BOOL hasMerchantId_:1;
  Float32 lat;
  Float32 lng;
  Float32 rate;
  int32_t cost;
  NSString* imgUrl;
  NSString* wapUrl;
  NSString* webUrl;
  NSString* siteUrl;
  NSString* workTime;
  NSString* desc;
  NSString* cate;
  NSString* tel;
  NSString* addr;
  NSString* county;
  NSString* name;
  NSString* aibangId;
  NSString* merchantId;
  NSMutableArray* mutablePromotionsList;
}
- (BOOL) hasMerchantId;
- (BOOL) hasAibangId;
- (BOOL) hasName;
- (BOOL) hasCounty;
- (BOOL) hasAddr;
- (BOOL) hasTel;
- (BOOL) hasCate;
- (BOOL) hasRate;
- (BOOL) hasCost;
- (BOOL) hasDesc;
- (BOOL) hasLng;
- (BOOL) hasLat;
- (BOOL) hasWorkTime;
- (BOOL) hasSiteUrl;
- (BOOL) hasWebUrl;
- (BOOL) hasWapUrl;
- (BOOL) hasImgUrl;
@property (readonly, retain) NSString* merchantId;
@property (readonly, retain) NSString* aibangId;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* county;
@property (readonly, retain) NSString* addr;
@property (readonly, retain) NSString* tel;
@property (readonly, retain) NSString* cate;
@property (readonly) Float32 rate;
@property (readonly) int32_t cost;
@property (readonly, retain) NSString* desc;
@property (readonly) Float32 lng;
@property (readonly) Float32 lat;
@property (readonly, retain) NSString* workTime;
@property (readonly, retain) NSString* siteUrl;
@property (readonly, retain) NSString* webUrl;
@property (readonly, retain) NSString* wapUrl;
@property (readonly, retain) NSString* imgUrl;
- (NSArray*) promotionsList;
- (PBPromotion*) promotionsAtIndex:(int32_t) index;

+ (PBMerchant*) defaultInstance;
- (PBMerchant*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBMerchant_Builder*) builder;
+ (PBMerchant_Builder*) builder;
+ (PBMerchant_Builder*) builderWithPrototype:(PBMerchant*) prototype;

+ (PBMerchant*) parseFromData:(NSData*) data;
+ (PBMerchant*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMerchant*) parseFromInputStream:(NSInputStream*) input;
+ (PBMerchant*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMerchant*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBMerchant*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBMerchant_Builder : PBGeneratedMessage_Builder {
@private
  PBMerchant* result;
}

- (PBMerchant*) defaultInstance;

- (PBMerchant_Builder*) clear;
- (PBMerchant_Builder*) clone;

- (PBMerchant*) build;
- (PBMerchant*) buildPartial;

- (PBMerchant_Builder*) mergeFrom:(PBMerchant*) other;
- (PBMerchant_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBMerchant_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMerchantId;
- (NSString*) merchantId;
- (PBMerchant_Builder*) setMerchantId:(NSString*) value;
- (PBMerchant_Builder*) clearMerchantId;

- (BOOL) hasAibangId;
- (NSString*) aibangId;
- (PBMerchant_Builder*) setAibangId:(NSString*) value;
- (PBMerchant_Builder*) clearAibangId;

- (BOOL) hasName;
- (NSString*) name;
- (PBMerchant_Builder*) setName:(NSString*) value;
- (PBMerchant_Builder*) clearName;

- (BOOL) hasCounty;
- (NSString*) county;
- (PBMerchant_Builder*) setCounty:(NSString*) value;
- (PBMerchant_Builder*) clearCounty;

- (BOOL) hasAddr;
- (NSString*) addr;
- (PBMerchant_Builder*) setAddr:(NSString*) value;
- (PBMerchant_Builder*) clearAddr;

- (BOOL) hasTel;
- (NSString*) tel;
- (PBMerchant_Builder*) setTel:(NSString*) value;
- (PBMerchant_Builder*) clearTel;

- (BOOL) hasCate;
- (NSString*) cate;
- (PBMerchant_Builder*) setCate:(NSString*) value;
- (PBMerchant_Builder*) clearCate;

- (BOOL) hasRate;
- (Float32) rate;
- (PBMerchant_Builder*) setRate:(Float32) value;
- (PBMerchant_Builder*) clearRate;

- (BOOL) hasCost;
- (int32_t) cost;
- (PBMerchant_Builder*) setCost:(int32_t) value;
- (PBMerchant_Builder*) clearCost;

- (BOOL) hasDesc;
- (NSString*) desc;
- (PBMerchant_Builder*) setDesc:(NSString*) value;
- (PBMerchant_Builder*) clearDesc;

- (BOOL) hasLng;
- (Float32) lng;
- (PBMerchant_Builder*) setLng:(Float32) value;
- (PBMerchant_Builder*) clearLng;

- (BOOL) hasLat;
- (Float32) lat;
- (PBMerchant_Builder*) setLat:(Float32) value;
- (PBMerchant_Builder*) clearLat;

- (BOOL) hasWorkTime;
- (NSString*) workTime;
- (PBMerchant_Builder*) setWorkTime:(NSString*) value;
- (PBMerchant_Builder*) clearWorkTime;

- (BOOL) hasSiteUrl;
- (NSString*) siteUrl;
- (PBMerchant_Builder*) setSiteUrl:(NSString*) value;
- (PBMerchant_Builder*) clearSiteUrl;

- (BOOL) hasWebUrl;
- (NSString*) webUrl;
- (PBMerchant_Builder*) setWebUrl:(NSString*) value;
- (PBMerchant_Builder*) clearWebUrl;

- (BOOL) hasWapUrl;
- (NSString*) wapUrl;
- (PBMerchant_Builder*) setWapUrl:(NSString*) value;
- (PBMerchant_Builder*) clearWapUrl;

- (BOOL) hasImgUrl;
- (NSString*) imgUrl;
- (PBMerchant_Builder*) setImgUrl:(NSString*) value;
- (PBMerchant_Builder*) clearImgUrl;

- (NSArray*) promotionsList;
- (PBPromotion*) promotionsAtIndex:(int32_t) index;
- (PBMerchant_Builder*) replacePromotionsAtIndex:(int32_t) index with:(PBPromotion*) value;
- (PBMerchant_Builder*) addPromotions:(PBPromotion*) value;
- (PBMerchant_Builder*) addAllPromotions:(NSArray*) values;
- (PBMerchant_Builder*) clearPromotionsList;
@end

@interface PBParty : PBGeneratedMessage {
@private
  BOOL hasMemberLimit_:1;
  BOOL hasJoinDeadtime_:1;
  BOOL hasHoldTime_:1;
  BOOL hasContent_:1;
  BOOL hasMerchant_:1;
  BOOL hasLocation_:1;
  BOOL hasContact_:1;
  BOOL hasPayType_:1;
  int32_t memberLimit;
  int32_t joinDeadtime;
  int32_t holdTime;
  NSString* content;
  PBMerchant* merchant;
  PBLocation* location;
  PBContact* contact;
  PBPayType payType;
  NSMutableArray* mutablePhotoListList;
}
- (BOOL) hasMerchant;
- (BOOL) hasMemberLimit;
- (BOOL) hasLocation;
- (BOOL) hasContact;
- (BOOL) hasJoinDeadtime;
- (BOOL) hasHoldTime;
- (BOOL) hasContent;
- (BOOL) hasPayType;
@property (readonly, retain) PBMerchant* merchant;
@property (readonly) int32_t memberLimit;
@property (readonly, retain) PBLocation* location;
@property (readonly, retain) PBContact* contact;
@property (readonly) int32_t joinDeadtime;
@property (readonly) int32_t holdTime;
@property (readonly, retain) NSString* content;
@property (readonly) PBPayType payType;
- (NSArray*) photoListList;
- (NSString*) photoListAtIndex:(int32_t) index;

+ (PBParty*) defaultInstance;
- (PBParty*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBParty_Builder*) builder;
+ (PBParty_Builder*) builder;
+ (PBParty_Builder*) builderWithPrototype:(PBParty*) prototype;

+ (PBParty*) parseFromData:(NSData*) data;
+ (PBParty*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBParty*) parseFromInputStream:(NSInputStream*) input;
+ (PBParty*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBParty*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBParty*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBParty_Builder : PBGeneratedMessage_Builder {
@private
  PBParty* result;
}

- (PBParty*) defaultInstance;

- (PBParty_Builder*) clear;
- (PBParty_Builder*) clone;

- (PBParty*) build;
- (PBParty*) buildPartial;

- (PBParty_Builder*) mergeFrom:(PBParty*) other;
- (PBParty_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBParty_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMerchant;
- (PBMerchant*) merchant;
- (PBParty_Builder*) setMerchant:(PBMerchant*) value;
- (PBParty_Builder*) setMerchantBuilder:(PBMerchant_Builder*) builderForValue;
- (PBParty_Builder*) mergeMerchant:(PBMerchant*) value;
- (PBParty_Builder*) clearMerchant;

- (BOOL) hasMemberLimit;
- (int32_t) memberLimit;
- (PBParty_Builder*) setMemberLimit:(int32_t) value;
- (PBParty_Builder*) clearMemberLimit;

- (BOOL) hasLocation;
- (PBLocation*) location;
- (PBParty_Builder*) setLocation:(PBLocation*) value;
- (PBParty_Builder*) setLocationBuilder:(PBLocation_Builder*) builderForValue;
- (PBParty_Builder*) mergeLocation:(PBLocation*) value;
- (PBParty_Builder*) clearLocation;

- (BOOL) hasContact;
- (PBContact*) contact;
- (PBParty_Builder*) setContact:(PBContact*) value;
- (PBParty_Builder*) setContactBuilder:(PBContact_Builder*) builderForValue;
- (PBParty_Builder*) mergeContact:(PBContact*) value;
- (PBParty_Builder*) clearContact;

- (BOOL) hasJoinDeadtime;
- (int32_t) joinDeadtime;
- (PBParty_Builder*) setJoinDeadtime:(int32_t) value;
- (PBParty_Builder*) clearJoinDeadtime;

- (BOOL) hasHoldTime;
- (int32_t) holdTime;
- (PBParty_Builder*) setHoldTime:(int32_t) value;
- (PBParty_Builder*) clearHoldTime;

- (BOOL) hasContent;
- (NSString*) content;
- (PBParty_Builder*) setContent:(NSString*) value;
- (PBParty_Builder*) clearContent;

- (NSArray*) photoListList;
- (NSString*) photoListAtIndex:(int32_t) index;
- (PBParty_Builder*) replacePhotoListAtIndex:(int32_t) index with:(NSString*) value;
- (PBParty_Builder*) addPhotoList:(NSString*) value;
- (PBParty_Builder*) addAllPhotoList:(NSArray*) values;
- (PBParty_Builder*) clearPhotoListList;

- (BOOL) hasPayType;
- (PBPayType) payType;
- (PBParty_Builder*) setPayType:(PBPayType) value;
- (PBParty_Builder*) clearPayType;
@end

@interface PBTraffic : PBGeneratedMessage {
@private
  BOOL hasMemberLimit_:1;
  BOOL hasJoinDeadtime_:1;
  BOOL hasHoldTime_:1;
  BOOL hasContent_:1;
  BOOL hasStartLoc_:1;
  BOOL hasEndLoc_:1;
  BOOL hasContact_:1;
  BOOL hasPayType_:1;
  int32_t memberLimit;
  int32_t joinDeadtime;
  int32_t holdTime;
  NSString* content;
  PBLocation* startLoc;
  PBLocation* endLoc;
  PBContact* contact;
  PBPayType payType;
}
- (BOOL) hasMemberLimit;
- (BOOL) hasStartLoc;
- (BOOL) hasEndLoc;
- (BOOL) hasContact;
- (BOOL) hasJoinDeadtime;
- (BOOL) hasHoldTime;
- (BOOL) hasContent;
- (BOOL) hasPayType;
@property (readonly) int32_t memberLimit;
@property (readonly, retain) PBLocation* startLoc;
@property (readonly, retain) PBLocation* endLoc;
@property (readonly, retain) PBContact* contact;
@property (readonly) int32_t joinDeadtime;
@property (readonly) int32_t holdTime;
@property (readonly, retain) NSString* content;
@property (readonly) PBPayType payType;

+ (PBTraffic*) defaultInstance;
- (PBTraffic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBTraffic_Builder*) builder;
+ (PBTraffic_Builder*) builder;
+ (PBTraffic_Builder*) builderWithPrototype:(PBTraffic*) prototype;

+ (PBTraffic*) parseFromData:(NSData*) data;
+ (PBTraffic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBTraffic*) parseFromInputStream:(NSInputStream*) input;
+ (PBTraffic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBTraffic_Builder : PBGeneratedMessage_Builder {
@private
  PBTraffic* result;
}

- (PBTraffic*) defaultInstance;

- (PBTraffic_Builder*) clear;
- (PBTraffic_Builder*) clone;

- (PBTraffic*) build;
- (PBTraffic*) buildPartial;

- (PBTraffic_Builder*) mergeFrom:(PBTraffic*) other;
- (PBTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMemberLimit;
- (int32_t) memberLimit;
- (PBTraffic_Builder*) setMemberLimit:(int32_t) value;
- (PBTraffic_Builder*) clearMemberLimit;

- (BOOL) hasStartLoc;
- (PBLocation*) startLoc;
- (PBTraffic_Builder*) setStartLoc:(PBLocation*) value;
- (PBTraffic_Builder*) setStartLocBuilder:(PBLocation_Builder*) builderForValue;
- (PBTraffic_Builder*) mergeStartLoc:(PBLocation*) value;
- (PBTraffic_Builder*) clearStartLoc;

- (BOOL) hasEndLoc;
- (PBLocation*) endLoc;
- (PBTraffic_Builder*) setEndLoc:(PBLocation*) value;
- (PBTraffic_Builder*) setEndLocBuilder:(PBLocation_Builder*) builderForValue;
- (PBTraffic_Builder*) mergeEndLoc:(PBLocation*) value;
- (PBTraffic_Builder*) clearEndLoc;

- (BOOL) hasContact;
- (PBContact*) contact;
- (PBTraffic_Builder*) setContact:(PBContact*) value;
- (PBTraffic_Builder*) setContactBuilder:(PBContact_Builder*) builderForValue;
- (PBTraffic_Builder*) mergeContact:(PBContact*) value;
- (PBTraffic_Builder*) clearContact;

- (BOOL) hasJoinDeadtime;
- (int32_t) joinDeadtime;
- (PBTraffic_Builder*) setJoinDeadtime:(int32_t) value;
- (PBTraffic_Builder*) clearJoinDeadtime;

- (BOOL) hasHoldTime;
- (int32_t) holdTime;
- (PBTraffic_Builder*) setHoldTime:(int32_t) value;
- (PBTraffic_Builder*) clearHoldTime;

- (BOOL) hasContent;
- (NSString*) content;
- (PBTraffic_Builder*) setContent:(NSString*) value;
- (PBTraffic_Builder*) clearContent;

- (BOOL) hasPayType;
- (PBPayType) payType;
- (PBTraffic_Builder*) setPayType:(PBPayType) value;
- (PBTraffic_Builder*) clearPayType;
@end

@interface PBShopping : PBGeneratedMessage {
@private
  BOOL hasMemberLimit_:1;
  BOOL hasJoinDeadtime_:1;
  BOOL hasHoldTime_:1;
  BOOL hasContent_:1;
  BOOL hasMerchant_:1;
  BOOL hasLocation_:1;
  BOOL hasContact_:1;
  BOOL hasPayType_:1;
  int32_t memberLimit;
  int32_t joinDeadtime;
  int32_t holdTime;
  NSString* content;
  PBMerchant* merchant;
  PBLocation* location;
  PBContact* contact;
  PBPayType payType;
  NSMutableArray* mutablePhotoListList;
}
- (BOOL) hasMerchant;
- (BOOL) hasMemberLimit;
- (BOOL) hasLocation;
- (BOOL) hasContact;
- (BOOL) hasJoinDeadtime;
- (BOOL) hasHoldTime;
- (BOOL) hasContent;
- (BOOL) hasPayType;
@property (readonly, retain) PBMerchant* merchant;
@property (readonly) int32_t memberLimit;
@property (readonly, retain) PBLocation* location;
@property (readonly, retain) PBContact* contact;
@property (readonly) int32_t joinDeadtime;
@property (readonly) int32_t holdTime;
@property (readonly, retain) NSString* content;
@property (readonly) PBPayType payType;
- (NSArray*) photoListList;
- (NSString*) photoListAtIndex:(int32_t) index;

+ (PBShopping*) defaultInstance;
- (PBShopping*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBShopping_Builder*) builder;
+ (PBShopping_Builder*) builder;
+ (PBShopping_Builder*) builderWithPrototype:(PBShopping*) prototype;

+ (PBShopping*) parseFromData:(NSData*) data;
+ (PBShopping*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBShopping*) parseFromInputStream:(NSInputStream*) input;
+ (PBShopping*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBShopping*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBShopping*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBShopping_Builder : PBGeneratedMessage_Builder {
@private
  PBShopping* result;
}

- (PBShopping*) defaultInstance;

- (PBShopping_Builder*) clear;
- (PBShopping_Builder*) clone;

- (PBShopping*) build;
- (PBShopping*) buildPartial;

- (PBShopping_Builder*) mergeFrom:(PBShopping*) other;
- (PBShopping_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBShopping_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMerchant;
- (PBMerchant*) merchant;
- (PBShopping_Builder*) setMerchant:(PBMerchant*) value;
- (PBShopping_Builder*) setMerchantBuilder:(PBMerchant_Builder*) builderForValue;
- (PBShopping_Builder*) mergeMerchant:(PBMerchant*) value;
- (PBShopping_Builder*) clearMerchant;

- (BOOL) hasMemberLimit;
- (int32_t) memberLimit;
- (PBShopping_Builder*) setMemberLimit:(int32_t) value;
- (PBShopping_Builder*) clearMemberLimit;

- (BOOL) hasLocation;
- (PBLocation*) location;
- (PBShopping_Builder*) setLocation:(PBLocation*) value;
- (PBShopping_Builder*) setLocationBuilder:(PBLocation_Builder*) builderForValue;
- (PBShopping_Builder*) mergeLocation:(PBLocation*) value;
- (PBShopping_Builder*) clearLocation;

- (BOOL) hasContact;
- (PBContact*) contact;
- (PBShopping_Builder*) setContact:(PBContact*) value;
- (PBShopping_Builder*) setContactBuilder:(PBContact_Builder*) builderForValue;
- (PBShopping_Builder*) mergeContact:(PBContact*) value;
- (PBShopping_Builder*) clearContact;

- (BOOL) hasJoinDeadtime;
- (int32_t) joinDeadtime;
- (PBShopping_Builder*) setJoinDeadtime:(int32_t) value;
- (PBShopping_Builder*) clearJoinDeadtime;

- (BOOL) hasHoldTime;
- (int32_t) holdTime;
- (PBShopping_Builder*) setHoldTime:(int32_t) value;
- (PBShopping_Builder*) clearHoldTime;

- (BOOL) hasContent;
- (NSString*) content;
- (PBShopping_Builder*) setContent:(NSString*) value;
- (PBShopping_Builder*) clearContent;

- (NSArray*) photoListList;
- (NSString*) photoListAtIndex:(int32_t) index;
- (PBShopping_Builder*) replacePhotoListAtIndex:(int32_t) index with:(NSString*) value;
- (PBShopping_Builder*) addPhotoList:(NSString*) value;
- (PBShopping_Builder*) addAllPhotoList:(NSArray*) values;
- (PBShopping_Builder*) clearPhotoListList;

- (BOOL) hasPayType;
- (PBPayType) payType;
- (PBShopping_Builder*) setPayType:(PBPayType) value;
- (PBShopping_Builder*) clearPayType;
@end

@interface PBActivity : PBGeneratedMessage {
@private
  BOOL hasCDate_:1;
  BOOL hasPrice_:1;
  BOOL hasCommentCount_:1;
  BOOL hasShareCount_:1;
  BOOL hasSignupCount_:1;
  BOOL hasParticipantCount_:1;
  BOOL hasMarkCount_:1;
  BOOL hasUid_:1;
  BOOL hasToken_:1;
  BOOL hasParty_:1;
  BOOL hasTraffic_:1;
  BOOL hasShopping_:1;
  BOOL hasType_:1;
  int32_t cDate;
  int32_t price;
  int32_t commentCount;
  int32_t shareCount;
  int32_t signupCount;
  int32_t participantCount;
  int32_t markCount;
  NSString* uid;
  NSString* token;
  PBParty* party;
  PBTraffic* traffic;
  PBShopping* shopping;
  PBActivityType type;
  NSMutableArray* mutableParticipantsList;
  NSMutableArray* mutableSignupsList;
}
- (BOOL) hasType;
- (BOOL) hasCDate;
- (BOOL) hasUid;
- (BOOL) hasToken;
- (BOOL) hasParty;
- (BOOL) hasTraffic;
- (BOOL) hasShopping;
- (BOOL) hasPrice;
- (BOOL) hasCommentCount;
- (BOOL) hasShareCount;
- (BOOL) hasSignupCount;
- (BOOL) hasParticipantCount;
- (BOOL) hasMarkCount;
@property (readonly) PBActivityType type;
@property (readonly) int32_t cDate;
@property (readonly, retain) NSString* uid;
@property (readonly, retain) NSString* token;
@property (readonly, retain) PBParty* party;
@property (readonly, retain) PBTraffic* traffic;
@property (readonly, retain) PBShopping* shopping;
@property (readonly) int32_t price;
@property (readonly) int32_t commentCount;
@property (readonly) int32_t shareCount;
@property (readonly) int32_t signupCount;
@property (readonly) int32_t participantCount;
@property (readonly) int32_t markCount;
- (NSArray*) participantsList;
- (NSString*) participantsAtIndex:(int32_t) index;
- (NSArray*) signupsList;
- (NSString*) signupsAtIndex:(int32_t) index;

+ (PBActivity*) defaultInstance;
- (PBActivity*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBActivity_Builder*) builder;
+ (PBActivity_Builder*) builder;
+ (PBActivity_Builder*) builderWithPrototype:(PBActivity*) prototype;

+ (PBActivity*) parseFromData:(NSData*) data;
+ (PBActivity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBActivity*) parseFromInputStream:(NSInputStream*) input;
+ (PBActivity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBActivity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBActivity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBActivity_Builder : PBGeneratedMessage_Builder {
@private
  PBActivity* result;
}

- (PBActivity*) defaultInstance;

- (PBActivity_Builder*) clear;
- (PBActivity_Builder*) clone;

- (PBActivity*) build;
- (PBActivity*) buildPartial;

- (PBActivity_Builder*) mergeFrom:(PBActivity*) other;
- (PBActivity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBActivity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (PBActivityType) type;
- (PBActivity_Builder*) setType:(PBActivityType) value;
- (PBActivity_Builder*) clearType;

- (BOOL) hasCDate;
- (int32_t) cDate;
- (PBActivity_Builder*) setCDate:(int32_t) value;
- (PBActivity_Builder*) clearCDate;

- (BOOL) hasUid;
- (NSString*) uid;
- (PBActivity_Builder*) setUid:(NSString*) value;
- (PBActivity_Builder*) clearUid;

- (BOOL) hasToken;
- (NSString*) token;
- (PBActivity_Builder*) setToken:(NSString*) value;
- (PBActivity_Builder*) clearToken;

- (BOOL) hasParty;
- (PBParty*) party;
- (PBActivity_Builder*) setParty:(PBParty*) value;
- (PBActivity_Builder*) setPartyBuilder:(PBParty_Builder*) builderForValue;
- (PBActivity_Builder*) mergeParty:(PBParty*) value;
- (PBActivity_Builder*) clearParty;

- (BOOL) hasTraffic;
- (PBTraffic*) traffic;
- (PBActivity_Builder*) setTraffic:(PBTraffic*) value;
- (PBActivity_Builder*) setTrafficBuilder:(PBTraffic_Builder*) builderForValue;
- (PBActivity_Builder*) mergeTraffic:(PBTraffic*) value;
- (PBActivity_Builder*) clearTraffic;

- (BOOL) hasShopping;
- (PBShopping*) shopping;
- (PBActivity_Builder*) setShopping:(PBShopping*) value;
- (PBActivity_Builder*) setShoppingBuilder:(PBShopping_Builder*) builderForValue;
- (PBActivity_Builder*) mergeShopping:(PBShopping*) value;
- (PBActivity_Builder*) clearShopping;

- (BOOL) hasPrice;
- (int32_t) price;
- (PBActivity_Builder*) setPrice:(int32_t) value;
- (PBActivity_Builder*) clearPrice;

- (NSArray*) participantsList;
- (NSString*) participantsAtIndex:(int32_t) index;
- (PBActivity_Builder*) replaceParticipantsAtIndex:(int32_t) index with:(NSString*) value;
- (PBActivity_Builder*) addParticipants:(NSString*) value;
- (PBActivity_Builder*) addAllParticipants:(NSArray*) values;
- (PBActivity_Builder*) clearParticipantsList;

- (NSArray*) signupsList;
- (NSString*) signupsAtIndex:(int32_t) index;
- (PBActivity_Builder*) replaceSignupsAtIndex:(int32_t) index with:(NSString*) value;
- (PBActivity_Builder*) addSignups:(NSString*) value;
- (PBActivity_Builder*) addAllSignups:(NSArray*) values;
- (PBActivity_Builder*) clearSignupsList;

- (BOOL) hasCommentCount;
- (int32_t) commentCount;
- (PBActivity_Builder*) setCommentCount:(int32_t) value;
- (PBActivity_Builder*) clearCommentCount;

- (BOOL) hasShareCount;
- (int32_t) shareCount;
- (PBActivity_Builder*) setShareCount:(int32_t) value;
- (PBActivity_Builder*) clearShareCount;

- (BOOL) hasSignupCount;
- (int32_t) signupCount;
- (PBActivity_Builder*) setSignupCount:(int32_t) value;
- (PBActivity_Builder*) clearSignupCount;

- (BOOL) hasParticipantCount;
- (int32_t) participantCount;
- (PBActivity_Builder*) setParticipantCount:(int32_t) value;
- (PBActivity_Builder*) clearParticipantCount;

- (BOOL) hasMarkCount;
- (int32_t) markCount;
- (PBActivity_Builder*) setMarkCount:(int32_t) value;
- (PBActivity_Builder*) clearMarkCount;
@end

@interface PBJoin : PBGeneratedMessage {
@private
  BOOL hasActivityId_:1;
  BOOL hasActivity_:1;
  NSString* activityId;
  PBActivity* activity;
}
- (BOOL) hasActivityId;
- (BOOL) hasActivity;
@property (readonly, retain) NSString* activityId;
@property (readonly, retain) PBActivity* activity;

+ (PBJoin*) defaultInstance;
- (PBJoin*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBJoin_Builder*) builder;
+ (PBJoin_Builder*) builder;
+ (PBJoin_Builder*) builderWithPrototype:(PBJoin*) prototype;

+ (PBJoin*) parseFromData:(NSData*) data;
+ (PBJoin*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBJoin*) parseFromInputStream:(NSInputStream*) input;
+ (PBJoin*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBJoin*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBJoin*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBJoin_Builder : PBGeneratedMessage_Builder {
@private
  PBJoin* result;
}

- (PBJoin*) defaultInstance;

- (PBJoin_Builder*) clear;
- (PBJoin_Builder*) clone;

- (PBJoin*) build;
- (PBJoin*) buildPartial;

- (PBJoin_Builder*) mergeFrom:(PBJoin*) other;
- (PBJoin_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBJoin_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasActivityId;
- (NSString*) activityId;
- (PBJoin_Builder*) setActivityId:(NSString*) value;
- (PBJoin_Builder*) clearActivityId;

- (BOOL) hasActivity;
- (PBActivity*) activity;
- (PBJoin_Builder*) setActivity:(PBActivity*) value;
- (PBJoin_Builder*) setActivityBuilder:(PBActivity_Builder*) builderForValue;
- (PBJoin_Builder*) mergeActivity:(PBActivity*) value;
- (PBJoin_Builder*) clearActivity;
@end

@interface PBShare : PBGeneratedMessage {
@private
  BOOL hasActivityId_:1;
  BOOL hasComment_:1;
  BOOL hasActivity_:1;
  NSString* activityId;
  NSString* comment;
  PBActivity* activity;
}
- (BOOL) hasActivityId;
- (BOOL) hasActivity;
- (BOOL) hasComment;
@property (readonly, retain) NSString* activityId;
@property (readonly, retain) PBActivity* activity;
@property (readonly, retain) NSString* comment;

+ (PBShare*) defaultInstance;
- (PBShare*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBShare_Builder*) builder;
+ (PBShare_Builder*) builder;
+ (PBShare_Builder*) builderWithPrototype:(PBShare*) prototype;

+ (PBShare*) parseFromData:(NSData*) data;
+ (PBShare*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBShare*) parseFromInputStream:(NSInputStream*) input;
+ (PBShare*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBShare*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBShare*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBShare_Builder : PBGeneratedMessage_Builder {
@private
  PBShare* result;
}

- (PBShare*) defaultInstance;

- (PBShare_Builder*) clear;
- (PBShare_Builder*) clone;

- (PBShare*) build;
- (PBShare*) buildPartial;

- (PBShare_Builder*) mergeFrom:(PBShare*) other;
- (PBShare_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBShare_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasActivityId;
- (NSString*) activityId;
- (PBShare_Builder*) setActivityId:(NSString*) value;
- (PBShare_Builder*) clearActivityId;

- (BOOL) hasActivity;
- (PBActivity*) activity;
- (PBShare_Builder*) setActivity:(PBActivity*) value;
- (PBShare_Builder*) setActivityBuilder:(PBActivity_Builder*) builderForValue;
- (PBShare_Builder*) mergeActivity:(PBActivity*) value;
- (PBShare_Builder*) clearActivity;

- (BOOL) hasComment;
- (NSString*) comment;
- (PBShare_Builder*) setComment:(NSString*) value;
- (PBShare_Builder*) clearComment;
@end

@interface PBAction : PBGeneratedMessage {
@private
  BOOL hasCDate_:1;
  BOOL hasActionId_:1;
  BOOL hasUser_:1;
  BOOL hasActivity_:1;
  BOOL hasShare_:1;
  BOOL hasJoin_:1;
  BOOL hasType_:1;
  int32_t cDate;
  NSString* actionId;
  PBUserBasic* user;
  PBActivity* activity;
  PBShare* share;
  PBJoin* join;
  PBActionType type;
}
- (BOOL) hasActionId;
- (BOOL) hasType;
- (BOOL) hasCDate;
- (BOOL) hasUser;
- (BOOL) hasActivity;
- (BOOL) hasShare;
- (BOOL) hasJoin;
@property (readonly, retain) NSString* actionId;
@property (readonly) PBActionType type;
@property (readonly) int32_t cDate;
@property (readonly, retain) PBUserBasic* user;
@property (readonly, retain) PBActivity* activity;
@property (readonly, retain) PBShare* share;
@property (readonly, retain) PBJoin* join;

+ (PBAction*) defaultInstance;
- (PBAction*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBAction_Builder*) builder;
+ (PBAction_Builder*) builder;
+ (PBAction_Builder*) builderWithPrototype:(PBAction*) prototype;

+ (PBAction*) parseFromData:(NSData*) data;
+ (PBAction*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAction*) parseFromInputStream:(NSInputStream*) input;
+ (PBAction*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAction*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBAction*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBAction_Builder : PBGeneratedMessage_Builder {
@private
  PBAction* result;
}

- (PBAction*) defaultInstance;

- (PBAction_Builder*) clear;
- (PBAction_Builder*) clone;

- (PBAction*) build;
- (PBAction*) buildPartial;

- (PBAction_Builder*) mergeFrom:(PBAction*) other;
- (PBAction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBAction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasActionId;
- (NSString*) actionId;
- (PBAction_Builder*) setActionId:(NSString*) value;
- (PBAction_Builder*) clearActionId;

- (BOOL) hasType;
- (PBActionType) type;
- (PBAction_Builder*) setType:(PBActionType) value;
- (PBAction_Builder*) clearType;

- (BOOL) hasCDate;
- (int32_t) cDate;
- (PBAction_Builder*) setCDate:(int32_t) value;
- (PBAction_Builder*) clearCDate;

- (BOOL) hasUser;
- (PBUserBasic*) user;
- (PBAction_Builder*) setUser:(PBUserBasic*) value;
- (PBAction_Builder*) setUserBuilder:(PBUserBasic_Builder*) builderForValue;
- (PBAction_Builder*) mergeUser:(PBUserBasic*) value;
- (PBAction_Builder*) clearUser;

- (BOOL) hasActivity;
- (PBActivity*) activity;
- (PBAction_Builder*) setActivity:(PBActivity*) value;
- (PBAction_Builder*) setActivityBuilder:(PBActivity_Builder*) builderForValue;
- (PBAction_Builder*) mergeActivity:(PBActivity*) value;
- (PBAction_Builder*) clearActivity;

- (BOOL) hasShare;
- (PBShare*) share;
- (PBAction_Builder*) setShare:(PBShare*) value;
- (PBAction_Builder*) setShareBuilder:(PBShare_Builder*) builderForValue;
- (PBAction_Builder*) mergeShare:(PBShare*) value;
- (PBAction_Builder*) clearShare;

- (BOOL) hasJoin;
- (PBJoin*) join;
- (PBAction_Builder*) setJoin:(PBJoin*) value;
- (PBAction_Builder*) setJoinBuilder:(PBJoin_Builder*) builderForValue;
- (PBAction_Builder*) mergeJoin:(PBJoin*) value;
- (PBAction_Builder*) clearJoin;
@end

