// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Basic.pb.h"
#import "User.pb.h"

@class PBAction;
@class PBAction_Builder;
@class PBActivity;
@class PBActivity_Builder;
@class PBAlbum;
@class PBAlbum_Builder;
@class PBBriefUser;
@class PBBriefUser_Builder;
@class PBComment;
@class PBComment_Builder;
@class PBContact;
@class PBContact_Builder;
@class PBDevice;
@class PBDevice_Builder;
@class PBLocation;
@class PBLocation_Builder;
@class PBLog;
@class PBLog_Builder;
@class PBMerchant;
@class PBMerchant_Builder;
@class PBPromotion;
@class PBPromotion_Builder;
@class PBRegistration;
@class PBRegistration_Builder;
@class PBSNS;
@class PBSNS_Builder;
@class PBStatistic;
@class PBStatistic_Builder;
@class PBUser;
@class PBUserBasic;
@class PBUserBasic_Builder;
@class PBUser_Builder;
typedef enum {
  PBActivityTypeParty = 1,
  PBActivityTypeTraffic = 2,
  PBActivityTypeShopping = 3,
} PBActivityType;

BOOL PBActivityTypeIsValidValue(PBActivityType value);

typedef enum {
  PBActionTypeActivity = 1,
  PBActionTypeShare = 2,
  PBActionTypeJoin = 3,
} PBActionType;

BOOL PBActionTypeIsValidValue(PBActionType value);

typedef enum {
  PBActionStatusNormal = 1,
  PBActionStatusDeleted = 2,
  PBActionStatusMark = 3,
} PBActionStatus;

BOOL PBActionStatusIsValidValue(PBActionStatus value);

typedef enum {
  PBPromotionStatusRunning = 0,
  PBPromotionStatusEnd = 1,
  PBPromotionStatusPendding = 2,
} PBPromotionStatus;

BOOL PBPromotionStatusIsValidValue(PBPromotionStatus value);

typedef enum {
  PBPayTypeAa = 1,
  PBPayTypeFree = 2,
  PBPayTypeOther = 10,
} PBPayType;

BOOL PBPayTypeIsValidValue(PBPayType value);


@interface ActionRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PBAlbum : PBGeneratedMessage {
@private
  BOOL hasAlbumId_:1;
  BOOL hasName_:1;
  BOOL hasUser_:1;
  NSString* albumId;
  NSString* name;
  PBBriefUser* user;
  NSMutableArray* mutableImageListList;
}
- (BOOL) hasAlbumId;
- (BOOL) hasUser;
- (BOOL) hasName;
@property (readonly, retain) NSString* albumId;
@property (readonly, retain) PBBriefUser* user;
@property (readonly, retain) NSString* name;
- (NSArray*) imageListList;
- (NSString*) imageListAtIndex:(int32_t) index;

+ (PBAlbum*) defaultInstance;
- (PBAlbum*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBAlbum_Builder*) builder;
+ (PBAlbum_Builder*) builder;
+ (PBAlbum_Builder*) builderWithPrototype:(PBAlbum*) prototype;

+ (PBAlbum*) parseFromData:(NSData*) data;
+ (PBAlbum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAlbum*) parseFromInputStream:(NSInputStream*) input;
+ (PBAlbum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAlbum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBAlbum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBAlbum_Builder : PBGeneratedMessage_Builder {
@private
  PBAlbum* result;
}

- (PBAlbum*) defaultInstance;

- (PBAlbum_Builder*) clear;
- (PBAlbum_Builder*) clone;

- (PBAlbum*) build;
- (PBAlbum*) buildPartial;

- (PBAlbum_Builder*) mergeFrom:(PBAlbum*) other;
- (PBAlbum_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBAlbum_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAlbumId;
- (NSString*) albumId;
- (PBAlbum_Builder*) setAlbumId:(NSString*) value;
- (PBAlbum_Builder*) clearAlbumId;

- (BOOL) hasUser;
- (PBBriefUser*) user;
- (PBAlbum_Builder*) setUser:(PBBriefUser*) value;
- (PBAlbum_Builder*) setUserBuilder:(PBBriefUser_Builder*) builderForValue;
- (PBAlbum_Builder*) mergeUser:(PBBriefUser*) value;
- (PBAlbum_Builder*) clearUser;

- (BOOL) hasName;
- (NSString*) name;
- (PBAlbum_Builder*) setName:(NSString*) value;
- (PBAlbum_Builder*) clearName;

- (NSArray*) imageListList;
- (NSString*) imageListAtIndex:(int32_t) index;
- (PBAlbum_Builder*) replaceImageListAtIndex:(int32_t) index with:(NSString*) value;
- (PBAlbum_Builder*) addImageList:(NSString*) value;
- (PBAlbum_Builder*) addAllImageList:(NSArray*) values;
- (PBAlbum_Builder*) clearImageListList;
@end

@interface PBPromotion : PBGeneratedMessage {
@private
  BOOL hasStartDate_:1;
  BOOL hasEndDate_:1;
  BOOL hasPromotionId_:1;
  BOOL hasTitle_:1;
  BOOL hasContent_:1;
  BOOL hasMerchantId_:1;
  BOOL hasStatus_:1;
  int32_t startDate;
  int32_t endDate;
  NSString* promotionId;
  NSString* title;
  NSString* content;
  NSString* merchantId;
  PBPromotionStatus status;
}
- (BOOL) hasPromotionId;
- (BOOL) hasStartDate;
- (BOOL) hasEndDate;
- (BOOL) hasTitle;
- (BOOL) hasContent;
- (BOOL) hasStatus;
- (BOOL) hasMerchantId;
@property (readonly, retain) NSString* promotionId;
@property (readonly) int32_t startDate;
@property (readonly) int32_t endDate;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* content;
@property (readonly) PBPromotionStatus status;
@property (readonly, retain) NSString* merchantId;

+ (PBPromotion*) defaultInstance;
- (PBPromotion*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBPromotion_Builder*) builder;
+ (PBPromotion_Builder*) builder;
+ (PBPromotion_Builder*) builderWithPrototype:(PBPromotion*) prototype;

+ (PBPromotion*) parseFromData:(NSData*) data;
+ (PBPromotion*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPromotion*) parseFromInputStream:(NSInputStream*) input;
+ (PBPromotion*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBPromotion*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBPromotion*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBPromotion_Builder : PBGeneratedMessage_Builder {
@private
  PBPromotion* result;
}

- (PBPromotion*) defaultInstance;

- (PBPromotion_Builder*) clear;
- (PBPromotion_Builder*) clone;

- (PBPromotion*) build;
- (PBPromotion*) buildPartial;

- (PBPromotion_Builder*) mergeFrom:(PBPromotion*) other;
- (PBPromotion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBPromotion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPromotionId;
- (NSString*) promotionId;
- (PBPromotion_Builder*) setPromotionId:(NSString*) value;
- (PBPromotion_Builder*) clearPromotionId;

- (BOOL) hasStartDate;
- (int32_t) startDate;
- (PBPromotion_Builder*) setStartDate:(int32_t) value;
- (PBPromotion_Builder*) clearStartDate;

- (BOOL) hasEndDate;
- (int32_t) endDate;
- (PBPromotion_Builder*) setEndDate:(int32_t) value;
- (PBPromotion_Builder*) clearEndDate;

- (BOOL) hasTitle;
- (NSString*) title;
- (PBPromotion_Builder*) setTitle:(NSString*) value;
- (PBPromotion_Builder*) clearTitle;

- (BOOL) hasContent;
- (NSString*) content;
- (PBPromotion_Builder*) setContent:(NSString*) value;
- (PBPromotion_Builder*) clearContent;

- (BOOL) hasStatus;
- (PBPromotionStatus) status;
- (PBPromotion_Builder*) setStatus:(PBPromotionStatus) value;
- (PBPromotion_Builder*) clearStatus;

- (BOOL) hasMerchantId;
- (NSString*) merchantId;
- (PBPromotion_Builder*) setMerchantId:(NSString*) value;
- (PBPromotion_Builder*) clearMerchantId;
@end

@interface PBMerchant : PBGeneratedMessage {
@private
  BOOL hasLat_:1;
  BOOL hasLng_:1;
  BOOL hasRate_:1;
  BOOL hasCost_:1;
  BOOL hasImgUrl_:1;
  BOOL hasWapUrl_:1;
  BOOL hasWebUrl_:1;
  BOOL hasSiteUrl_:1;
  BOOL hasWorkTime_:1;
  BOOL hasDesc_:1;
  BOOL hasCate_:1;
  BOOL hasTel_:1;
  BOOL hasAddr_:1;
  BOOL hasCounty_:1;
  BOOL hasName_:1;
  BOOL hasAibangId_:1;
  BOOL hasMerchantId_:1;
  Float32 lat;
  Float32 lng;
  Float32 rate;
  int32_t cost;
  NSString* imgUrl;
  NSString* wapUrl;
  NSString* webUrl;
  NSString* siteUrl;
  NSString* workTime;
  NSString* desc;
  NSString* cate;
  NSString* tel;
  NSString* addr;
  NSString* county;
  NSString* name;
  NSString* aibangId;
  NSString* merchantId;
  NSMutableArray* mutablePromotionIdsList;
  NSMutableArray* mutablePromotionsList;
}
- (BOOL) hasMerchantId;
- (BOOL) hasAibangId;
- (BOOL) hasName;
- (BOOL) hasCounty;
- (BOOL) hasAddr;
- (BOOL) hasTel;
- (BOOL) hasCate;
- (BOOL) hasRate;
- (BOOL) hasCost;
- (BOOL) hasDesc;
- (BOOL) hasLng;
- (BOOL) hasLat;
- (BOOL) hasWorkTime;
- (BOOL) hasSiteUrl;
- (BOOL) hasWebUrl;
- (BOOL) hasWapUrl;
- (BOOL) hasImgUrl;
@property (readonly, retain) NSString* merchantId;
@property (readonly, retain) NSString* aibangId;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* county;
@property (readonly, retain) NSString* addr;
@property (readonly, retain) NSString* tel;
@property (readonly, retain) NSString* cate;
@property (readonly) Float32 rate;
@property (readonly) int32_t cost;
@property (readonly, retain) NSString* desc;
@property (readonly) Float32 lng;
@property (readonly) Float32 lat;
@property (readonly, retain) NSString* workTime;
@property (readonly, retain) NSString* siteUrl;
@property (readonly, retain) NSString* webUrl;
@property (readonly, retain) NSString* wapUrl;
@property (readonly, retain) NSString* imgUrl;
- (NSArray*) promotionsList;
- (PBPromotion*) promotionsAtIndex:(int32_t) index;
- (NSArray*) promotionIdsList;
- (NSString*) promotionIdsAtIndex:(int32_t) index;

+ (PBMerchant*) defaultInstance;
- (PBMerchant*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBMerchant_Builder*) builder;
+ (PBMerchant_Builder*) builder;
+ (PBMerchant_Builder*) builderWithPrototype:(PBMerchant*) prototype;

+ (PBMerchant*) parseFromData:(NSData*) data;
+ (PBMerchant*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMerchant*) parseFromInputStream:(NSInputStream*) input;
+ (PBMerchant*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMerchant*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBMerchant*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBMerchant_Builder : PBGeneratedMessage_Builder {
@private
  PBMerchant* result;
}

- (PBMerchant*) defaultInstance;

- (PBMerchant_Builder*) clear;
- (PBMerchant_Builder*) clone;

- (PBMerchant*) build;
- (PBMerchant*) buildPartial;

- (PBMerchant_Builder*) mergeFrom:(PBMerchant*) other;
- (PBMerchant_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBMerchant_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMerchantId;
- (NSString*) merchantId;
- (PBMerchant_Builder*) setMerchantId:(NSString*) value;
- (PBMerchant_Builder*) clearMerchantId;

- (BOOL) hasAibangId;
- (NSString*) aibangId;
- (PBMerchant_Builder*) setAibangId:(NSString*) value;
- (PBMerchant_Builder*) clearAibangId;

- (BOOL) hasName;
- (NSString*) name;
- (PBMerchant_Builder*) setName:(NSString*) value;
- (PBMerchant_Builder*) clearName;

- (BOOL) hasCounty;
- (NSString*) county;
- (PBMerchant_Builder*) setCounty:(NSString*) value;
- (PBMerchant_Builder*) clearCounty;

- (BOOL) hasAddr;
- (NSString*) addr;
- (PBMerchant_Builder*) setAddr:(NSString*) value;
- (PBMerchant_Builder*) clearAddr;

- (BOOL) hasTel;
- (NSString*) tel;
- (PBMerchant_Builder*) setTel:(NSString*) value;
- (PBMerchant_Builder*) clearTel;

- (BOOL) hasCate;
- (NSString*) cate;
- (PBMerchant_Builder*) setCate:(NSString*) value;
- (PBMerchant_Builder*) clearCate;

- (BOOL) hasRate;
- (Float32) rate;
- (PBMerchant_Builder*) setRate:(Float32) value;
- (PBMerchant_Builder*) clearRate;

- (BOOL) hasCost;
- (int32_t) cost;
- (PBMerchant_Builder*) setCost:(int32_t) value;
- (PBMerchant_Builder*) clearCost;

- (BOOL) hasDesc;
- (NSString*) desc;
- (PBMerchant_Builder*) setDesc:(NSString*) value;
- (PBMerchant_Builder*) clearDesc;

- (BOOL) hasLng;
- (Float32) lng;
- (PBMerchant_Builder*) setLng:(Float32) value;
- (PBMerchant_Builder*) clearLng;

- (BOOL) hasLat;
- (Float32) lat;
- (PBMerchant_Builder*) setLat:(Float32) value;
- (PBMerchant_Builder*) clearLat;

- (BOOL) hasWorkTime;
- (NSString*) workTime;
- (PBMerchant_Builder*) setWorkTime:(NSString*) value;
- (PBMerchant_Builder*) clearWorkTime;

- (BOOL) hasSiteUrl;
- (NSString*) siteUrl;
- (PBMerchant_Builder*) setSiteUrl:(NSString*) value;
- (PBMerchant_Builder*) clearSiteUrl;

- (BOOL) hasWebUrl;
- (NSString*) webUrl;
- (PBMerchant_Builder*) setWebUrl:(NSString*) value;
- (PBMerchant_Builder*) clearWebUrl;

- (BOOL) hasWapUrl;
- (NSString*) wapUrl;
- (PBMerchant_Builder*) setWapUrl:(NSString*) value;
- (PBMerchant_Builder*) clearWapUrl;

- (BOOL) hasImgUrl;
- (NSString*) imgUrl;
- (PBMerchant_Builder*) setImgUrl:(NSString*) value;
- (PBMerchant_Builder*) clearImgUrl;

- (NSArray*) promotionsList;
- (PBPromotion*) promotionsAtIndex:(int32_t) index;
- (PBMerchant_Builder*) replacePromotionsAtIndex:(int32_t) index with:(PBPromotion*) value;
- (PBMerchant_Builder*) addPromotions:(PBPromotion*) value;
- (PBMerchant_Builder*) addAllPromotions:(NSArray*) values;
- (PBMerchant_Builder*) clearPromotionsList;

- (NSArray*) promotionIdsList;
- (NSString*) promotionIdsAtIndex:(int32_t) index;
- (PBMerchant_Builder*) replacePromotionIdsAtIndex:(int32_t) index with:(NSString*) value;
- (PBMerchant_Builder*) addPromotionIds:(NSString*) value;
- (PBMerchant_Builder*) addAllPromotionIds:(NSArray*) values;
- (PBMerchant_Builder*) clearPromotionIdsList;
@end

@interface PBActivity : PBGeneratedMessage {
@private
  BOOL hasBudget_:1;
  BOOL hasPrice_:1;
  BOOL hasJoinDeadtime_:1;
  BOOL hasHoldDeadtime_:1;
  BOOL hasMemberLimit_:1;
  BOOL hasMarkCount_:1;
  BOOL hasCommentCount_:1;
  BOOL hasShareCount_:1;
  BOOL hasParticipantCount_:1;
  BOOL hasToken_:1;
  BOOL hasEndLoc_:1;
  BOOL hasContent_:1;
  BOOL hasStartLoc_:1;
  BOOL hasLocation_:1;
  BOOL hasMerchant_:1;
  BOOL hasPayType_:1;
  BOOL hasType_:1;
  Float32 budget;
  Float32 price;
  int32_t joinDeadtime;
  int32_t holdDeadtime;
  int32_t memberLimit;
  int32_t markCount;
  int32_t commentCount;
  int32_t shareCount;
  int32_t participantCount;
  NSString* token;
  PBLocation* endLoc;
  PBContact* content;
  PBLocation* startLoc;
  PBLocation* location;
  PBMerchant* merchant;
  PBPayType payType;
  PBActivityType type;
  NSMutableArray* mutableSignupsList;
  NSMutableArray* mutableParticipantsList;
  NSMutableArray* mutablePhotoListList;
}
- (BOOL) hasType;
- (BOOL) hasToken;
- (BOOL) hasContent;
- (BOOL) hasJoinDeadtime;
- (BOOL) hasHoldDeadtime;
- (BOOL) hasPayType;
- (BOOL) hasBudget;
- (BOOL) hasPrice;
- (BOOL) hasMemberLimit;
- (BOOL) hasCommentCount;
- (BOOL) hasShareCount;
- (BOOL) hasParticipantCount;
- (BOOL) hasMarkCount;
- (BOOL) hasMerchant;
- (BOOL) hasLocation;
- (BOOL) hasStartLoc;
- (BOOL) hasEndLoc;
@property (readonly) PBActivityType type;
@property (readonly, retain) NSString* token;
@property (readonly, retain) PBContact* content;
@property (readonly) int32_t joinDeadtime;
@property (readonly) int32_t holdDeadtime;
@property (readonly) PBPayType payType;
@property (readonly) Float32 budget;
@property (readonly) Float32 price;
@property (readonly) int32_t memberLimit;
@property (readonly) int32_t commentCount;
@property (readonly) int32_t shareCount;
@property (readonly) int32_t participantCount;
@property (readonly) int32_t markCount;
@property (readonly, retain) PBMerchant* merchant;
@property (readonly, retain) PBLocation* location;
@property (readonly, retain) PBLocation* startLoc;
@property (readonly, retain) PBLocation* endLoc;
- (NSArray*) photoListList;
- (NSString*) photoListAtIndex:(int32_t) index;
- (NSArray*) participantsList;
- (NSString*) participantsAtIndex:(int32_t) index;
- (NSArray*) signupsList;
- (NSString*) signupsAtIndex:(int32_t) index;

+ (PBActivity*) defaultInstance;
- (PBActivity*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBActivity_Builder*) builder;
+ (PBActivity_Builder*) builder;
+ (PBActivity_Builder*) builderWithPrototype:(PBActivity*) prototype;

+ (PBActivity*) parseFromData:(NSData*) data;
+ (PBActivity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBActivity*) parseFromInputStream:(NSInputStream*) input;
+ (PBActivity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBActivity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBActivity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBActivity_Builder : PBGeneratedMessage_Builder {
@private
  PBActivity* result;
}

- (PBActivity*) defaultInstance;

- (PBActivity_Builder*) clear;
- (PBActivity_Builder*) clone;

- (PBActivity*) build;
- (PBActivity*) buildPartial;

- (PBActivity_Builder*) mergeFrom:(PBActivity*) other;
- (PBActivity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBActivity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (PBActivityType) type;
- (PBActivity_Builder*) setType:(PBActivityType) value;
- (PBActivity_Builder*) clearType;

- (BOOL) hasToken;
- (NSString*) token;
- (PBActivity_Builder*) setToken:(NSString*) value;
- (PBActivity_Builder*) clearToken;

- (BOOL) hasContent;
- (PBContact*) content;
- (PBActivity_Builder*) setContent:(PBContact*) value;
- (PBActivity_Builder*) setContentBuilder:(PBContact_Builder*) builderForValue;
- (PBActivity_Builder*) mergeContent:(PBContact*) value;
- (PBActivity_Builder*) clearContent;

- (BOOL) hasJoinDeadtime;
- (int32_t) joinDeadtime;
- (PBActivity_Builder*) setJoinDeadtime:(int32_t) value;
- (PBActivity_Builder*) clearJoinDeadtime;

- (BOOL) hasHoldDeadtime;
- (int32_t) holdDeadtime;
- (PBActivity_Builder*) setHoldDeadtime:(int32_t) value;
- (PBActivity_Builder*) clearHoldDeadtime;

- (BOOL) hasPayType;
- (PBPayType) payType;
- (PBActivity_Builder*) setPayType:(PBPayType) value;
- (PBActivity_Builder*) clearPayType;

- (BOOL) hasBudget;
- (Float32) budget;
- (PBActivity_Builder*) setBudget:(Float32) value;
- (PBActivity_Builder*) clearBudget;

- (BOOL) hasPrice;
- (Float32) price;
- (PBActivity_Builder*) setPrice:(Float32) value;
- (PBActivity_Builder*) clearPrice;

- (BOOL) hasMemberLimit;
- (int32_t) memberLimit;
- (PBActivity_Builder*) setMemberLimit:(int32_t) value;
- (PBActivity_Builder*) clearMemberLimit;

- (NSArray*) photoListList;
- (NSString*) photoListAtIndex:(int32_t) index;
- (PBActivity_Builder*) replacePhotoListAtIndex:(int32_t) index with:(NSString*) value;
- (PBActivity_Builder*) addPhotoList:(NSString*) value;
- (PBActivity_Builder*) addAllPhotoList:(NSArray*) values;
- (PBActivity_Builder*) clearPhotoListList;

- (NSArray*) participantsList;
- (NSString*) participantsAtIndex:(int32_t) index;
- (PBActivity_Builder*) replaceParticipantsAtIndex:(int32_t) index with:(NSString*) value;
- (PBActivity_Builder*) addParticipants:(NSString*) value;
- (PBActivity_Builder*) addAllParticipants:(NSArray*) values;
- (PBActivity_Builder*) clearParticipantsList;

- (NSArray*) signupsList;
- (NSString*) signupsAtIndex:(int32_t) index;
- (PBActivity_Builder*) replaceSignupsAtIndex:(int32_t) index with:(NSString*) value;
- (PBActivity_Builder*) addSignups:(NSString*) value;
- (PBActivity_Builder*) addAllSignups:(NSArray*) values;
- (PBActivity_Builder*) clearSignupsList;

- (BOOL) hasCommentCount;
- (int32_t) commentCount;
- (PBActivity_Builder*) setCommentCount:(int32_t) value;
- (PBActivity_Builder*) clearCommentCount;

- (BOOL) hasShareCount;
- (int32_t) shareCount;
- (PBActivity_Builder*) setShareCount:(int32_t) value;
- (PBActivity_Builder*) clearShareCount;

- (BOOL) hasParticipantCount;
- (int32_t) participantCount;
- (PBActivity_Builder*) setParticipantCount:(int32_t) value;
- (PBActivity_Builder*) clearParticipantCount;

- (BOOL) hasMarkCount;
- (int32_t) markCount;
- (PBActivity_Builder*) setMarkCount:(int32_t) value;
- (PBActivity_Builder*) clearMarkCount;

- (BOOL) hasMerchant;
- (PBMerchant*) merchant;
- (PBActivity_Builder*) setMerchant:(PBMerchant*) value;
- (PBActivity_Builder*) setMerchantBuilder:(PBMerchant_Builder*) builderForValue;
- (PBActivity_Builder*) mergeMerchant:(PBMerchant*) value;
- (PBActivity_Builder*) clearMerchant;

- (BOOL) hasLocation;
- (PBLocation*) location;
- (PBActivity_Builder*) setLocation:(PBLocation*) value;
- (PBActivity_Builder*) setLocationBuilder:(PBLocation_Builder*) builderForValue;
- (PBActivity_Builder*) mergeLocation:(PBLocation*) value;
- (PBActivity_Builder*) clearLocation;

- (BOOL) hasStartLoc;
- (PBLocation*) startLoc;
- (PBActivity_Builder*) setStartLoc:(PBLocation*) value;
- (PBActivity_Builder*) setStartLocBuilder:(PBLocation_Builder*) builderForValue;
- (PBActivity_Builder*) mergeStartLoc:(PBLocation*) value;
- (PBActivity_Builder*) clearStartLoc;

- (BOOL) hasEndLoc;
- (PBLocation*) endLoc;
- (PBActivity_Builder*) setEndLoc:(PBLocation*) value;
- (PBActivity_Builder*) setEndLocBuilder:(PBLocation_Builder*) builderForValue;
- (PBActivity_Builder*) mergeEndLoc:(PBLocation*) value;
- (PBActivity_Builder*) clearEndLoc;
@end

@interface PBAction : PBGeneratedMessage {
@private
  BOOL hasCDate_:1;
  BOOL hasActionId_:1;
  BOOL hasComment_:1;
  BOOL hasUser_:1;
  BOOL hasActivity_:1;
  BOOL hasRelatedAction_:1;
  BOOL hasType_:1;
  int32_t cDate;
  NSString* actionId;
  NSString* comment;
  PBBriefUser* user;
  PBActivity* activity;
  PBAction* relatedAction;
  PBActionType type;
}
- (BOOL) hasActionId;
- (BOOL) hasType;
- (BOOL) hasCDate;
- (BOOL) hasUser;
- (BOOL) hasActivity;
- (BOOL) hasComment;
- (BOOL) hasRelatedAction;
@property (readonly, retain) NSString* actionId;
@property (readonly) PBActionType type;
@property (readonly) int32_t cDate;
@property (readonly, retain) PBBriefUser* user;
@property (readonly, retain) PBActivity* activity;
@property (readonly, retain) NSString* comment;
@property (readonly, retain) PBAction* relatedAction;

+ (PBAction*) defaultInstance;
- (PBAction*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBAction_Builder*) builder;
+ (PBAction_Builder*) builder;
+ (PBAction_Builder*) builderWithPrototype:(PBAction*) prototype;

+ (PBAction*) parseFromData:(NSData*) data;
+ (PBAction*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAction*) parseFromInputStream:(NSInputStream*) input;
+ (PBAction*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBAction*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBAction*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBAction_Builder : PBGeneratedMessage_Builder {
@private
  PBAction* result;
}

- (PBAction*) defaultInstance;

- (PBAction_Builder*) clear;
- (PBAction_Builder*) clone;

- (PBAction*) build;
- (PBAction*) buildPartial;

- (PBAction_Builder*) mergeFrom:(PBAction*) other;
- (PBAction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBAction_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasActionId;
- (NSString*) actionId;
- (PBAction_Builder*) setActionId:(NSString*) value;
- (PBAction_Builder*) clearActionId;

- (BOOL) hasType;
- (PBActionType) type;
- (PBAction_Builder*) setType:(PBActionType) value;
- (PBAction_Builder*) clearType;

- (BOOL) hasCDate;
- (int32_t) cDate;
- (PBAction_Builder*) setCDate:(int32_t) value;
- (PBAction_Builder*) clearCDate;

- (BOOL) hasUser;
- (PBBriefUser*) user;
- (PBAction_Builder*) setUser:(PBBriefUser*) value;
- (PBAction_Builder*) setUserBuilder:(PBBriefUser_Builder*) builderForValue;
- (PBAction_Builder*) mergeUser:(PBBriefUser*) value;
- (PBAction_Builder*) clearUser;

- (BOOL) hasActivity;
- (PBActivity*) activity;
- (PBAction_Builder*) setActivity:(PBActivity*) value;
- (PBAction_Builder*) setActivityBuilder:(PBActivity_Builder*) builderForValue;
- (PBAction_Builder*) mergeActivity:(PBActivity*) value;
- (PBAction_Builder*) clearActivity;

- (BOOL) hasComment;
- (NSString*) comment;
- (PBAction_Builder*) setComment:(NSString*) value;
- (PBAction_Builder*) clearComment;

- (BOOL) hasRelatedAction;
- (PBAction*) relatedAction;
- (PBAction_Builder*) setRelatedAction:(PBAction*) value;
- (PBAction_Builder*) setRelatedActionBuilder:(PBAction_Builder*) builderForValue;
- (PBAction_Builder*) mergeRelatedAction:(PBAction*) value;
- (PBAction_Builder*) clearRelatedAction;
@end

@interface PBComment : PBGeneratedMessage {
@private
  BOOL hasIsReply_:1;
  BOOL hasCDate_:1;
  BOOL hasStar_:1;
  BOOL hasCommentId_:1;
  BOOL hasActionId_:1;
  BOOL hasContent_:1;
  BOOL hasReplyActionId_:1;
  BOOL hasDigest_:1;
  BOOL hasUser_:1;
  BOOL isReply_:1;
  int32_t cDate;
  int32_t star;
  NSString* commentId;
  NSString* actionId;
  NSString* content;
  NSString* replyActionId;
  NSString* digest;
  PBBriefUser* user;
}
- (BOOL) hasCommentId;
- (BOOL) hasUser;
- (BOOL) hasCDate;
- (BOOL) hasActionId;
- (BOOL) hasContent;
- (BOOL) hasStar;
- (BOOL) hasIsReply;
- (BOOL) hasReplyActionId;
- (BOOL) hasDigest;
@property (readonly, retain) NSString* commentId;
@property (readonly, retain) PBBriefUser* user;
@property (readonly) int32_t cDate;
@property (readonly, retain) NSString* actionId;
@property (readonly, retain) NSString* content;
@property (readonly) int32_t star;
- (BOOL) isReply;
@property (readonly, retain) NSString* replyActionId;
@property (readonly, retain) NSString* digest;

+ (PBComment*) defaultInstance;
- (PBComment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBComment_Builder*) builder;
+ (PBComment_Builder*) builder;
+ (PBComment_Builder*) builderWithPrototype:(PBComment*) prototype;

+ (PBComment*) parseFromData:(NSData*) data;
+ (PBComment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBComment*) parseFromInputStream:(NSInputStream*) input;
+ (PBComment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBComment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBComment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBComment_Builder : PBGeneratedMessage_Builder {
@private
  PBComment* result;
}

- (PBComment*) defaultInstance;

- (PBComment_Builder*) clear;
- (PBComment_Builder*) clone;

- (PBComment*) build;
- (PBComment*) buildPartial;

- (PBComment_Builder*) mergeFrom:(PBComment*) other;
- (PBComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCommentId;
- (NSString*) commentId;
- (PBComment_Builder*) setCommentId:(NSString*) value;
- (PBComment_Builder*) clearCommentId;

- (BOOL) hasUser;
- (PBBriefUser*) user;
- (PBComment_Builder*) setUser:(PBBriefUser*) value;
- (PBComment_Builder*) setUserBuilder:(PBBriefUser_Builder*) builderForValue;
- (PBComment_Builder*) mergeUser:(PBBriefUser*) value;
- (PBComment_Builder*) clearUser;

- (BOOL) hasCDate;
- (int32_t) cDate;
- (PBComment_Builder*) setCDate:(int32_t) value;
- (PBComment_Builder*) clearCDate;

- (BOOL) hasActionId;
- (NSString*) actionId;
- (PBComment_Builder*) setActionId:(NSString*) value;
- (PBComment_Builder*) clearActionId;

- (BOOL) hasContent;
- (NSString*) content;
- (PBComment_Builder*) setContent:(NSString*) value;
- (PBComment_Builder*) clearContent;

- (BOOL) hasStar;
- (int32_t) star;
- (PBComment_Builder*) setStar:(int32_t) value;
- (PBComment_Builder*) clearStar;

- (BOOL) hasIsReply;
- (BOOL) isReply;
- (PBComment_Builder*) setIsReply:(BOOL) value;
- (PBComment_Builder*) clearIsReply;

- (BOOL) hasReplyActionId;
- (NSString*) replyActionId;
- (PBComment_Builder*) setReplyActionId:(NSString*) value;
- (PBComment_Builder*) clearReplyActionId;

- (BOOL) hasDigest;
- (NSString*) digest;
- (PBComment_Builder*) setDigest:(NSString*) value;
- (PBComment_Builder*) clearDigest;
@end

