// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Basic.pb.h"

@implementation BasicRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [BasicRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PBLocation ()
@property int32_t countryCode;
@property (retain) NSString* province;
@property (retain) NSString* city;
@property Float32 latitude;
@property Float32 longitude;
@end

@implementation PBLocation

- (BOOL) hasCountryCode {
  return !!hasCountryCode_;
}
- (void) setHasCountryCode:(BOOL) value {
  hasCountryCode_ = !!value;
}
@synthesize countryCode;
- (BOOL) hasProvince {
  return !!hasProvince_;
}
- (void) setHasProvince:(BOOL) value {
  hasProvince_ = !!value;
}
@synthesize province;
- (BOOL) hasCity {
  return !!hasCity_;
}
- (void) setHasCity:(BOOL) value {
  hasCity_ = !!value;
}
@synthesize city;
- (BOOL) hasLatitude {
  return !!hasLatitude_;
}
- (void) setHasLatitude:(BOOL) value {
  hasLatitude_ = !!value;
}
@synthesize latitude;
- (BOOL) hasLongitude {
  return !!hasLongitude_;
}
- (void) setHasLongitude:(BOOL) value {
  hasLongitude_ = !!value;
}
@synthesize longitude;
- (void) dealloc {
  self.province = nil;
  self.city = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.countryCode = 0;
    self.province = @"";
    self.city = @"";
    self.latitude = 0;
    self.longitude = 0;
  }
  return self;
}
static PBLocation* defaultPBLocationInstance = nil;
+ (void) initialize {
  if (self == [PBLocation class]) {
    defaultPBLocationInstance = [[PBLocation alloc] init];
  }
}
+ (PBLocation*) defaultInstance {
  return defaultPBLocationInstance;
}
- (PBLocation*) defaultInstance {
  return defaultPBLocationInstance;
}
- (BOOL) isInitialized {
  if (!self.hasCountryCode) {
    return NO;
  }
  if (!self.hasProvince) {
    return NO;
  }
  if (!self.hasCity) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCountryCode) {
    [output writeInt32:1 value:self.countryCode];
  }
  if (self.hasProvince) {
    [output writeString:2 value:self.province];
  }
  if (self.hasCity) {
    [output writeString:3 value:self.city];
  }
  if (self.hasLatitude) {
    [output writeFloat:4 value:self.latitude];
  }
  if (self.hasLongitude) {
    [output writeFloat:5 value:self.longitude];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasCountryCode) {
    size += computeInt32Size(1, self.countryCode);
  }
  if (self.hasProvince) {
    size += computeStringSize(2, self.province);
  }
  if (self.hasCity) {
    size += computeStringSize(3, self.city);
  }
  if (self.hasLatitude) {
    size += computeFloatSize(4, self.latitude);
  }
  if (self.hasLongitude) {
    size += computeFloatSize(5, self.longitude);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (PBLocation*) parseFromData:(NSData*) data {
  return (PBLocation*)[[[PBLocation builder] mergeFromData:data] build];
}
+ (PBLocation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBLocation*)[[[PBLocation builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PBLocation*) parseFromInputStream:(NSInputStream*) input {
  return (PBLocation*)[[[PBLocation builder] mergeFromInputStream:input] build];
}
+ (PBLocation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBLocation*)[[[PBLocation builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PBLocation*)[[[PBLocation builder] mergeFromCodedInputStream:input] build];
}
+ (PBLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBLocation*)[[[PBLocation builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBLocation_Builder*) builder {
  return [[[PBLocation_Builder alloc] init] autorelease];
}
+ (PBLocation_Builder*) builderWithPrototype:(PBLocation*) prototype {
  return [[PBLocation builder] mergeFrom:prototype];
}
- (PBLocation_Builder*) builder {
  return [PBLocation builder];
}
@end

@interface PBLocation_Builder()
@property (retain) PBLocation* result;
@end

@implementation PBLocation_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PBLocation alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PBLocation_Builder*) clear {
  self.result = [[[PBLocation alloc] init] autorelease];
  return self;
}
- (PBLocation_Builder*) clone {
  return [PBLocation builderWithPrototype:result];
}
- (PBLocation*) defaultInstance {
  return [PBLocation defaultInstance];
}
- (PBLocation*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PBLocation*) buildPartial {
  PBLocation* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PBLocation_Builder*) mergeFrom:(PBLocation*) other {
  if (other == [PBLocation defaultInstance]) {
    return self;
  }
  if (other.hasCountryCode) {
    [self setCountryCode:other.countryCode];
  }
  if (other.hasProvince) {
    [self setProvince:other.province];
  }
  if (other.hasCity) {
    [self setCity:other.city];
  }
  if (other.hasLatitude) {
    [self setLatitude:other.latitude];
  }
  if (other.hasLongitude) {
    [self setLongitude:other.longitude];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PBLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PBLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setCountryCode:[input readInt32]];
        break;
      }
      case 18: {
        [self setProvince:[input readString]];
        break;
      }
      case 26: {
        [self setCity:[input readString]];
        break;
      }
      case 37: {
        [self setLatitude:[input readFloat]];
        break;
      }
      case 45: {
        [self setLongitude:[input readFloat]];
        break;
      }
    }
  }
}
- (BOOL) hasCountryCode {
  return result.hasCountryCode;
}
- (int32_t) countryCode {
  return result.countryCode;
}
- (PBLocation_Builder*) setCountryCode:(int32_t) value {
  result.hasCountryCode = YES;
  result.countryCode = value;
  return self;
}
- (PBLocation_Builder*) clearCountryCode {
  result.hasCountryCode = NO;
  result.countryCode = 0;
  return self;
}
- (BOOL) hasProvince {
  return result.hasProvince;
}
- (NSString*) province {
  return result.province;
}
- (PBLocation_Builder*) setProvince:(NSString*) value {
  result.hasProvince = YES;
  result.province = value;
  return self;
}
- (PBLocation_Builder*) clearProvince {
  result.hasProvince = NO;
  result.province = @"";
  return self;
}
- (BOOL) hasCity {
  return result.hasCity;
}
- (NSString*) city {
  return result.city;
}
- (PBLocation_Builder*) setCity:(NSString*) value {
  result.hasCity = YES;
  result.city = value;
  return self;
}
- (PBLocation_Builder*) clearCity {
  result.hasCity = NO;
  result.city = @"";
  return self;
}
- (BOOL) hasLatitude {
  return result.hasLatitude;
}
- (Float32) latitude {
  return result.latitude;
}
- (PBLocation_Builder*) setLatitude:(Float32) value {
  result.hasLatitude = YES;
  result.latitude = value;
  return self;
}
- (PBLocation_Builder*) clearLatitude {
  result.hasLatitude = NO;
  result.latitude = 0;
  return self;
}
- (BOOL) hasLongitude {
  return result.hasLongitude;
}
- (Float32) longitude {
  return result.longitude;
}
- (PBLocation_Builder*) setLongitude:(Float32) value {
  result.hasLongitude = YES;
  result.longitude = value;
  return self;
}
- (PBLocation_Builder*) clearLongitude {
  result.hasLongitude = NO;
  result.longitude = 0;
  return self;
}
@end

@interface PBContact ()
@property (retain) NSMutableArray* mutableTelNumberList;
@end

@implementation PBContact

@synthesize mutableTelNumberList;
- (void) dealloc {
  self.mutableTelNumberList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static PBContact* defaultPBContactInstance = nil;
+ (void) initialize {
  if (self == [PBContact class]) {
    defaultPBContactInstance = [[PBContact alloc] init];
  }
}
+ (PBContact*) defaultInstance {
  return defaultPBContactInstance;
}
- (PBContact*) defaultInstance {
  return defaultPBContactInstance;
}
- (NSArray*) telNumberList {
  return mutableTelNumberList;
}
- (NSString*) telNumberAtIndex:(int32_t) index {
  id value = [mutableTelNumberList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (NSString* element in self.mutableTelNumberList) {
    [output writeString:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  {
    int32_t dataSize = 0;
    for (NSString* element in self.mutableTelNumberList) {
      dataSize += computeStringSizeNoTag(element);
    }
    size += dataSize;
    size += 1 * self.mutableTelNumberList.count;
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (PBContact*) parseFromData:(NSData*) data {
  return (PBContact*)[[[PBContact builder] mergeFromData:data] build];
}
+ (PBContact*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBContact*)[[[PBContact builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PBContact*) parseFromInputStream:(NSInputStream*) input {
  return (PBContact*)[[[PBContact builder] mergeFromInputStream:input] build];
}
+ (PBContact*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBContact*)[[[PBContact builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBContact*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PBContact*)[[[PBContact builder] mergeFromCodedInputStream:input] build];
}
+ (PBContact*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PBContact*)[[[PBContact builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PBContact_Builder*) builder {
  return [[[PBContact_Builder alloc] init] autorelease];
}
+ (PBContact_Builder*) builderWithPrototype:(PBContact*) prototype {
  return [[PBContact builder] mergeFrom:prototype];
}
- (PBContact_Builder*) builder {
  return [PBContact builder];
}
@end

@interface PBContact_Builder()
@property (retain) PBContact* result;
@end

@implementation PBContact_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PBContact alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PBContact_Builder*) clear {
  self.result = [[[PBContact alloc] init] autorelease];
  return self;
}
- (PBContact_Builder*) clone {
  return [PBContact builderWithPrototype:result];
}
- (PBContact*) defaultInstance {
  return [PBContact defaultInstance];
}
- (PBContact*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PBContact*) buildPartial {
  PBContact* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PBContact_Builder*) mergeFrom:(PBContact*) other {
  if (other == [PBContact defaultInstance]) {
    return self;
  }
  if (other.mutableTelNumberList.count > 0) {
    if (result.mutableTelNumberList == nil) {
      result.mutableTelNumberList = [NSMutableArray array];
    }
    [result.mutableTelNumberList addObjectsFromArray:other.mutableTelNumberList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PBContact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PBContact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self addTelNumber:[input readString]];
        break;
      }
    }
  }
}
- (NSArray*) telNumberList {
  if (result.mutableTelNumberList == nil) {
    return [NSArray array];
  }
  return result.mutableTelNumberList;
}
- (NSString*) telNumberAtIndex:(int32_t) index {
  return [result telNumberAtIndex:index];
}
- (PBContact_Builder*) replaceTelNumberAtIndex:(int32_t) index with:(NSString*) value {
  [result.mutableTelNumberList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (PBContact_Builder*) addTelNumber:(NSString*) value {
  if (result.mutableTelNumberList == nil) {
    result.mutableTelNumberList = [NSMutableArray array];
  }
  [result.mutableTelNumberList addObject:value];
  return self;
}
- (PBContact_Builder*) addAllTelNumber:(NSArray*) values {
  if (result.mutableTelNumberList == nil) {
    result.mutableTelNumberList = [NSMutableArray array];
  }
  [result.mutableTelNumberList addObjectsFromArray:values];
  return self;
}
- (PBContact_Builder*) clearTelNumberList {
  result.mutableTelNumberList = nil;
  return self;
}
@end

