// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class PBContact;
@class PBContact_Builder;
@class PBLocation;
@class PBLocation_Builder;

@interface BasicRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PBLocation : PBGeneratedMessage {
@private
  BOOL hasLatitude_:1;
  BOOL hasLongitude_:1;
  BOOL hasCountryCode_:1;
  BOOL hasProvince_:1;
  BOOL hasCity_:1;
  Float32 latitude;
  Float32 longitude;
  int32_t countryCode;
  NSString* province;
  NSString* city;
}
- (BOOL) hasCountryCode;
- (BOOL) hasProvince;
- (BOOL) hasCity;
- (BOOL) hasLatitude;
- (BOOL) hasLongitude;
@property (readonly) int32_t countryCode;
@property (readonly, retain) NSString* province;
@property (readonly, retain) NSString* city;
@property (readonly) Float32 latitude;
@property (readonly) Float32 longitude;

+ (PBLocation*) defaultInstance;
- (PBLocation*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBLocation_Builder*) builder;
+ (PBLocation_Builder*) builder;
+ (PBLocation_Builder*) builderWithPrototype:(PBLocation*) prototype;

+ (PBLocation*) parseFromData:(NSData*) data;
+ (PBLocation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBLocation*) parseFromInputStream:(NSInputStream*) input;
+ (PBLocation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBLocation_Builder : PBGeneratedMessage_Builder {
@private
  PBLocation* result;
}

- (PBLocation*) defaultInstance;

- (PBLocation_Builder*) clear;
- (PBLocation_Builder*) clone;

- (PBLocation*) build;
- (PBLocation*) buildPartial;

- (PBLocation_Builder*) mergeFrom:(PBLocation*) other;
- (PBLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCountryCode;
- (int32_t) countryCode;
- (PBLocation_Builder*) setCountryCode:(int32_t) value;
- (PBLocation_Builder*) clearCountryCode;

- (BOOL) hasProvince;
- (NSString*) province;
- (PBLocation_Builder*) setProvince:(NSString*) value;
- (PBLocation_Builder*) clearProvince;

- (BOOL) hasCity;
- (NSString*) city;
- (PBLocation_Builder*) setCity:(NSString*) value;
- (PBLocation_Builder*) clearCity;

- (BOOL) hasLatitude;
- (Float32) latitude;
- (PBLocation_Builder*) setLatitude:(Float32) value;
- (PBLocation_Builder*) clearLatitude;

- (BOOL) hasLongitude;
- (Float32) longitude;
- (PBLocation_Builder*) setLongitude:(Float32) value;
- (PBLocation_Builder*) clearLongitude;
@end

@interface PBContact : PBGeneratedMessage {
@private
  NSMutableArray* mutableTelNumberList;
}
- (NSArray*) telNumberList;
- (NSString*) telNumberAtIndex:(int32_t) index;

+ (PBContact*) defaultInstance;
- (PBContact*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBContact_Builder*) builder;
+ (PBContact_Builder*) builder;
+ (PBContact_Builder*) builderWithPrototype:(PBContact*) prototype;

+ (PBContact*) parseFromData:(NSData*) data;
+ (PBContact*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBContact*) parseFromInputStream:(NSInputStream*) input;
+ (PBContact*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBContact*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBContact*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBContact_Builder : PBGeneratedMessage_Builder {
@private
  PBContact* result;
}

- (PBContact*) defaultInstance;

- (PBContact_Builder*) clear;
- (PBContact_Builder*) clone;

- (PBContact*) build;
- (PBContact*) buildPartial;

- (PBContact_Builder*) mergeFrom:(PBContact*) other;
- (PBContact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBContact_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) telNumberList;
- (NSString*) telNumberAtIndex:(int32_t) index;
- (PBContact_Builder*) replaceTelNumberAtIndex:(int32_t) index with:(NSString*) value;
- (PBContact_Builder*) addTelNumber:(NSString*) value;
- (PBContact_Builder*) addAllTelNumber:(NSArray*) values;
- (PBContact_Builder*) clearTelNumberList;
@end

