// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Basic.pb.h"

@class PBContact;
@class PBContact_Builder;
@class PBLocation;
@class PBLocation_Builder;
@class PBMessage;
@class PBMessage_Builder;
typedef enum {
  PBMessageTypeText = 1,
  PBMessageTypeImage = 2,
  PBMessageTypeSound = 3,
} PBMessageType;

BOOL PBMessageTypeIsValidValue(PBMessageType value);

typedef enum {
  PBMessageStatusUnread = 1,
  PBMessageStatusRead = 2,
  PBMessageStatusSending = 3,
  PBMessageStatusSent = 4,
} PBMessageStatus;

BOOL PBMessageStatusIsValidValue(PBMessageStatus value);


@interface MessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PBMessage : PBGeneratedMessage {
@private
  BOOL hasCDate_:1;
  BOOL hasMessageId_:1;
  BOOL hasFromUid_:1;
  BOOL hasToUid_:1;
  BOOL hasText_:1;
  BOOL hasImageUrl_:1;
  BOOL hasSoundUrl_:1;
  BOOL hasType_:1;
  BOOL hasStatus_:1;
  int32_t cDate;
  NSString* messageId;
  NSString* fromUid;
  NSString* toUid;
  NSString* text;
  NSString* imageUrl;
  NSString* soundUrl;
  PBMessageType type;
  PBMessageStatus status;
}
- (BOOL) hasMessageId;
- (BOOL) hasFromUid;
- (BOOL) hasToUid;
- (BOOL) hasType;
- (BOOL) hasStatus;
- (BOOL) hasCDate;
- (BOOL) hasText;
- (BOOL) hasImageUrl;
- (BOOL) hasSoundUrl;
@property (readonly, retain) NSString* messageId;
@property (readonly, retain) NSString* fromUid;
@property (readonly, retain) NSString* toUid;
@property (readonly) PBMessageType type;
@property (readonly) PBMessageStatus status;
@property (readonly) int32_t cDate;
@property (readonly, retain) NSString* text;
@property (readonly, retain) NSString* imageUrl;
@property (readonly, retain) NSString* soundUrl;

+ (PBMessage*) defaultInstance;
- (PBMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBMessage_Builder*) builder;
+ (PBMessage_Builder*) builder;
+ (PBMessage_Builder*) builderWithPrototype:(PBMessage*) prototype;

+ (PBMessage*) parseFromData:(NSData*) data;
+ (PBMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMessage*) parseFromInputStream:(NSInputStream*) input;
+ (PBMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBMessage_Builder : PBGeneratedMessage_Builder {
@private
  PBMessage* result;
}

- (PBMessage*) defaultInstance;

- (PBMessage_Builder*) clear;
- (PBMessage_Builder*) clone;

- (PBMessage*) build;
- (PBMessage*) buildPartial;

- (PBMessage_Builder*) mergeFrom:(PBMessage*) other;
- (PBMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageId;
- (NSString*) messageId;
- (PBMessage_Builder*) setMessageId:(NSString*) value;
- (PBMessage_Builder*) clearMessageId;

- (BOOL) hasFromUid;
- (NSString*) fromUid;
- (PBMessage_Builder*) setFromUid:(NSString*) value;
- (PBMessage_Builder*) clearFromUid;

- (BOOL) hasToUid;
- (NSString*) toUid;
- (PBMessage_Builder*) setToUid:(NSString*) value;
- (PBMessage_Builder*) clearToUid;

- (BOOL) hasType;
- (PBMessageType) type;
- (PBMessage_Builder*) setType:(PBMessageType) value;
- (PBMessage_Builder*) clearType;

- (BOOL) hasStatus;
- (PBMessageStatus) status;
- (PBMessage_Builder*) setStatus:(PBMessageStatus) value;
- (PBMessage_Builder*) clearStatus;

- (BOOL) hasCDate;
- (int32_t) cDate;
- (PBMessage_Builder*) setCDate:(int32_t) value;
- (PBMessage_Builder*) clearCDate;

- (BOOL) hasText;
- (NSString*) text;
- (PBMessage_Builder*) setText:(NSString*) value;
- (PBMessage_Builder*) clearText;

- (BOOL) hasImageUrl;
- (NSString*) imageUrl;
- (PBMessage_Builder*) setImageUrl:(NSString*) value;
- (PBMessage_Builder*) clearImageUrl;

- (BOOL) hasSoundUrl;
- (NSString*) soundUrl;
- (PBMessage_Builder*) setSoundUrl:(NSString*) value;
- (PBMessage_Builder*) clearSoundUrl;
@end

