//
//  ServiceConstants.h
//  JuJu
//
//  Created by ict on 13-7-24.
//  Copyright (c) 2013年 ict. All rights reserved.
//

///////////////REQUEST PATH///////////////
#define REGISTER  @"api/users/register"
#define SNSLOGIN  @"api/users/snslogin"
#define LOGIN  @"api/users/login"
#define LOGOUT  @"api/users/logout"
#define GET_PROFILE  @"api/users/get_profile"
#define UPDATE_PROFILE  @"api/users/update_profile"
#define BIND_SNS  @"api/users/bind_sns"
#define UPDATE_DEVICE  @"api/users/update_device"

#define FOLLOW  @"api/relations/follow"
#define UNFOLLOW  @"api/relations/unfollow"
#define BLACK_USER  @"api/relations/black_user"
#define UNBLACK_USER  @"api/relations/unblack_user"
#define MARK_FRIEND  @"api/relations/mark_friend"
#define GET_FANS  @"api/relations/get_fans"
#define GET_FOLLOWS  @"api/relations/get_follows"
#define GET_BLACKS  @"api/relations/get_blacks"



///////////////PARAMETERS///////////////

#define ACTION @"action"
#define ACTION_ID @"action_id"
#define ACTIVITY @"activity"
#define ACTIVITY_ID @"activity_id"
#define ADDR @"addr"
#define AIBANG_ID @"aibang_id"
#define ALBUM_ID @"album_id"
#define AVATAR @"avatar"
#define BIRTH_DATE @"birth_date"
#define C_DATE @"c_date"
#define CATE @"cate"
#define CITY @"city"
#define COMMENT @"comment"
#define COMMENT_COUNT @"comment_count"
#define COMMENT_ID @"comment_id"
#define CONTACT @"contact"
#define CONTENT @"content"
#define COST @"cost"
#define COUNTRY_CODE @"country_code"
#define COUNTY @"county"
#define DESC @"desc"
#define DEVICE_ID @"device_id"
#define DEVICE_INFO @"device_info"
#define DEVICE_NAME @"device_name"
#define DEVICE_OS @"device_os"
#define DEVICE_TOKEN @"device_token"
#define DIGEST @"digest"
#define END_DATE @"end_date"
#define END_LOC @"end_loc"
#define ERROR_MESSAGE @"error_message"
#define FAN_COUNT @"fan_count"
#define FOLLOW_COUNT @"follow_count"
#define FROM_UID @"from_uid"
#define GENDER @"gender"
#define HOLD_TIME @"hold_time"
#define IMAGE_LIST @"image_list"
#define IMAGE_URL @"image_url"
#define IMG_URL @"img_url"
#define INTRODUCTION @"introduction"
#define IS_REPLY @"is_reply"
#define JOIN @"join"
#define JOIN_DEADTIME @"join_deadtime"
#define LAST_LOG_DATE @"last_log_date"
#define LAST_LOG_IP @"last_log_ip"
#define LAST_LOG_LATITUDE @"last_log_latitude"
#define LAST_LOG_LONGITUDE @"last_log_longitude"
#define LAT @"lat"
#define LATITUDE @"latitude"
#define LNG @"lng"
#define LOCATION @"location"
#define LOG_INFO @"log_info"
#define LONGITUDE @"longitude"
#define MARK_COUNT @"mark_count"
#define MEMBER_LIMIT @"member_limit"
#define MERCHANT @"merchant"
#define MERCHANT_ID @"merchant_id"
#define MESSAGE_ID @"message_id"
#define MY_ACTIVITY @"my_activity"
#define NAME @"name"
#define NEW_FAN_COUNT @"new_fan_count"
#define NEW_FEED_COUNT @"new_feed_count"
#define NEW_FOLLOW_COUNT @"new_follow_count"
#define NEW_MESSAGE_COUNT @"new_message_count"
#define NEW_NOTICE_COUNT @"new_notice_count"
#define NICK @"nick"
#define NOTE_NAME @"note_name"
#define PARTICIPANT_COUNT @"participant_count"
#define PARTICIPANTS @"participants"
#define PARTY @"party"
#define PASSWORD @"password"
#define PAY_TYPE @"pay_type"
#define PHOTO_LIST @"photo_list"
#define PRICE @"price"
#define PROVINCE @"province"
#define QQ_NUMBER @"qq_number"
#define QQ_WEIBO_ID @"qq_weibo_id"
#define QQ_WEIBO_NICK @"qq_weibo_nick"
#define RATE @"rate"
#define REG_DATE @"reg_date"
#define REG_IP @"reg_ip"
#define REG_TYPE @"reg_type"
#define REGISTION @"registion"
#define RELATION @"relation"
#define RENREN_ID @"renren_id"
#define RENREN_NICK @"renren_nick"
#define REPLY_ID @"reply_id"
#define ROLE @"role"
#define SHARE @"share"
#define SHARE_COUNT @"share_count"
#define SHOPPING @"shopping"
#define SIGNUP_COUNT @"signup_count"
#define SIGNUPS @"signups"
#define SINA_WEIBO_ID @"sina_weibo_id"
#define SINA_WEIBO_NICK @"sina_weibo_nick"
#define SITE_URL @"site_url"
#define SNS_INFO @"sns_info"
#define SOUND_URL @"sound_url"
#define STAR @"star"
#define START_DATE @"start_date"
#define START_LOC @"start_loc"
#define STATISTIC @"statistic"
#define STATUS @"status"
#define TAGS @"tags"
#define TEL @"tel"
#define TEL_NUMBER @"tel_number"
#define TEXT @"text"
#define TO_UID @"to_uid"
#define TOKEN @"token"
#define TRAFFIC @"traffic"
#define UID @"uid"
#define UNAME @"uname"
#define USER @"user"
#define WAP_URL @"wap_url"
#define WEB_URL @"web_url"
#define WORK_TIME @"work_time"


#define TYPE @"type"
#define SNS_ID @"snsid"
#define SNS_NICK @"snsnick"
#define SNS_TOKEN @"snstoken"
#define IP @"ip"



//NEW
#define FID @"fid"
#define MARK @"mark"
#define OFFSET @"offset"
#define COUNT @"count"
